# NumPy Exercises 



#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10) # Create a an array of 10 zeros  using the numpy library 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10) # Create a an array of 10 ones using the numpy library 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [14]:
x=np.ones(10) # Create a an array of 10 ones  using the numpy library 

x[:]=5 # using Broadcasting to replace every value in every row and coloumn with 5

x # show the output 

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [17]:
np.random.randint(10,51,40) # use the randint function inside the method random to generate 40 number from 10 to 50

array([38, 27, 35, 35, 13, 18, 44, 13, 48, 40, 47, 39, 33, 40, 43, 18, 15,
       43, 23, 33, 37, 40, 14, 43, 42, 20, 45, 17, 11, 12, 31, 15, 45, 18,
       14, 11, 40, 30, 44, 10])

#### Create an array of all the even integers from 10 to 50

In [3]:
y=np.arange(10,51,1) # using the arange method to generate array start from 10 to 51 ( will end at 50) by step 1

bool_arr= y % 2 ==0  # Use The Condationing to return the even number
 
y[bool_arr] # return the true values of the condation 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [30]:
c=np.arange(0,9,1) # using the arange method to generate array start from 0 to 9 ( will end at 8) by step 1

c.reshape(3,3) # reshape the array into square matrix of 3,3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [31]:
np.eye(3,3) # Create a an identity Matrix of shape 3,3 using the numpy library 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [38]:
np.random.rand(1) # using function rand inside random method to generate a random number between zero and one 

array([0.88885487])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [39]:
np.random.randn(25) # using function randn inside random method to generate a 25 random numbers which follow the guassian distribution

array([ 1.17537339e+00,  1.18238761e+00,  7.66686621e-01, -3.23214677e-01,
       -5.42718919e-01,  5.01412776e-01,  6.10898380e-01, -7.58572921e-01,
       -4.76181649e-01,  1.12580976e+00, -3.95887593e-01, -6.70015069e-01,
        1.64668069e+00, -1.10738190e-03, -3.45937648e-02, -3.45401086e-02,
       -1.71310930e+00,  1.33214332e-01,  2.96232986e-01, -3.84911624e-01,
       -3.34939640e-01, -1.84066549e+00,  3.03369865e-01, -6.52923246e-01,
        1.01123563e+00])

#### Create the following matrix:

In [43]:
k=np.arange(0.01,1.01,0.01) #  using the arange method to generate array start from 0.01 to 1.01 ( end at 1.00) by step 0.01

k.reshape(10,10) # reshape the array into matrix of shape (10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [44]:
np.linspace(0,1,20) # generate random numbers from 0 to 1 

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [56]:
mat = np.arange(1,26).reshape(5,5) 
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [54]:
x=mat[2:,1:] # slice the given matrix to start from the third row ( index 2 ) and the second coloumn ( index 1 )
x

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [64]:
mat[3,4] # indexing the the fourth row ( index 3) and the fifth coloumn ( index 4)

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [65]:
m=mat[0:3,1:2] # slicing the matrix from index 0 ( first row ) to the third row ( index 2 ) and from the second coloumn (index 1) to the second coloumn ( index 1)
m

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [66]:
mat[4,0:]   # slicing the matrix from index 4 ( fifth row ) from the first coloumn (index 0) to the end

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [67]:
mat[3:,:]  # slicing the matrix from index 3 ( fourth row )  and from the first coloumn (index 0) to the end

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [50]:
np.sum(mat) # determine the sum of the values matrix 

325

#### Get the standard deviation of the values in mat

In [76]:
np.std(mat) # determine the standared devation of the matrix 

7.211102550927978

#### Get the sum of all the columns in mat

In [80]:
np.sum(mat,axis=0)  # determine the sum of the coloumns o f the matrix by giving the parameter axis the value '0' 

array([55, 60, 65, 70, 75])

# Great Job!