## Metrices Multiplication 

In [8]:
a=[[1,2,3],[4,5,6]]
b=[[1,2,3],[4,5,6]]
def multi_element_wise (v,w):
    assert len(v)==len(w)
    return [v_i * w_i for v_i , w_i in zip (v,w)]

def matrix_mult_element_wise(a,b):
    c=[]
    for i in range (len(a)):
        c.append(multi_element_wise(a[i],b[i]))
    return c

In [9]:
matrix_mult_element_wise(a,b)

[[1, 4, 9], [16, 25, 36]]

## Metrices-Vector Multiplication

In [47]:
m=[[1,2],[3,4],[5,6]]
vector1=[0.5,0.5]
def Matrix_Vector_Multiplication (m,v):
    assert len(m)==len(v)
    return sum([m_i * v_i for v_i , m_i in zip (m,v)])


In [23]:
def matrix_vector_mutlti(a,b):
    c=[]
    for i in range (len(a)):
        c.append(Matrix_Vector_Multiplication(a[i],b))
    return c

In [24]:
matrix_vector_mutlti(m,vector1)

[1.5, 3.5, 5.5]

## Matrix-Scaler Multiplicaiton

In [55]:
s=2
def Scaler_Multiplicaiton (c,v):
    return [c * v_i for v_i in v]

def Matrix_Scaler_Multiplicaiton(A,b):
    c=[]
    for i in range(len(A)):
        c.append(Scaler_Multiplicaiton(b,A[i]))
    return c

In [56]:
Matrix_Scaler_Multiplicaiton(m,s)

[[2, 4], [6, 8], [10, 12]]

# Numpy

In [57]:
import numpy as np # for array 'Linar Algebra & Math'

In [58]:
my_list=[1,2,3]
type(my_list)

list

In [59]:
np.array(my_list)

array([1, 2, 3])

In [60]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [63]:
x=np.array(my_matrix)

In [64]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
x.shape

(3, 3)

## arange

In [66]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Generate array of zeros and ones

In [69]:
np.zeros(3)

array([0., 0., 0.])

In [71]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
np.ones(3)

array([1., 1., 1.])

In [75]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [77]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### Eye 

In [79]:
np.eye(3) # Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

In [82]:
np.random.rand(3)  # generate numbers according to uniform distribution from 0 to 1 

array([0.07769555, 0.01985162, 0.8418539 ])

In [83]:
np.random.rand(5,5)  

array([[0.38753274, 0.75073374, 0.18935539, 0.12954159, 0.47985153],
       [0.4783999 , 0.30400414, 0.51927937, 0.1864929 , 0.72523365],
       [0.11777359, 0.62176972, 0.18297188, 0.87763484, 0.89464431],
       [0.14812169, 0.54435495, 0.1039779 , 0.56289591, 0.86396356],
       [0.46630616, 0.65145755, 0.50627969, 0.53943135, 0.84872909]])

In [92]:
np.random.randn(2) # generate numbers according to Normal distribution from -3.5 to 3.5 

array([-0.31758329, -0.82337589])

In [93]:
np.random.randn(5,5)

array([[-1.14064134,  0.08007293, -0.38885681, -0.1072898 , -0.49050102],
       [-0.88741213, -0.67393715, -1.29281399,  0.20894361, -0.35751926],
       [-1.65512704,  0.66471801, -0.24632557,  0.86760292, -0.40466501],
       [ 1.11571374, -0.98386167, -1.2327388 ,  1.02768837, -3.46136969],
       [-0.9435013 ,  0.99037197,  0.85443712, -1.54498258, -1.12830548]])

In [94]:
np.random.randint(1,100) # generate integer numbers 

60

In [95]:
np.random.randint(1,100,10) # generate integer numbers of 10 vectors

array([17, 72, 80, 75, 56, 61, 76, 84, 44, 34])

In [96]:
np.random.randint(1,100,(2,2)) # generate integer numbers of matrix

array([[95, 81],
       [85, 76]])

## Array Attributes and Methods 

In [97]:
arr =np.arange(25)

ranarr=np.random.randint(0,50,10)

In [98]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [99]:
ranarr

array([21, 16, 18, 49,  6,  2,  9, 21, 33, 26])

In [101]:
arr.reshape(5,5) # 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [102]:
ranarr.max() # return the maximum number of the array 

49

In [103]:
ranarr.argmax()   # return the location of  maximum number of the array 

3

In [104]:
ranarr.min()     # return the minimum number of the array 

2

In [105]:
ranarr.argmin()   # return the location of minimun number of the array 

5

# Numpy Indexing and Selection

In [106]:
# creating sample array
arr1=np.arange(0,11)

In [108]:
#Show 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Numpy Indexing and Selection

In [109]:
# get a value at an index 
arr[8]

8

In [110]:
#get values in a range 
arr[0:5]

array([0, 1, 2, 3, 4])

In [111]:
#get values in a range 
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [112]:
# setting a value with index range (BroadCasting)

arr1[0:5]=100

arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [113]:
# Reset Array m we 'kk'

In [116]:
# important notes and slices 
slice_of_arr= arr[0:6]

#show Slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [117]:
#change the slice 
slice_of_arr[:]=99

#show slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [118]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [120]:
# copy of the data 
copy_arr=arr.copy()

## Indexing a 2D Array ( Metrices ) 

In [121]:
arr_2d=np.array(([5,10,5],[20,25,30],[35,40,45]))

#show
arr_2d

array([[ 5, 10,  5],
       [20, 25, 30],
       [35, 40, 45]])

In [122]:
#indexing row 
arr_2d[0:2]

array([[ 5, 10,  5],
       [20, 25, 30]])

In [127]:
#format  is arr_2d [row][col]
arr_2d[0][1]
          

5

In [125]:
arr_2d[0,1]

10

In [128]:
# 2D  Slicing ( Rows , Colouns)
arr_2d[:2,0:]


array([[ 5, 10,  5],
       [20, 25, 30]])

In [129]:
# shape bottom row

arr_2d[2]

array([35, 40, 45])

## Selction 


In [133]:
arr > 7 

array([ True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [134]:
bool_arr = arr > 7


In [135]:
bool_arr

array([ True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [136]:
arr[bool_arr]

array([99, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [137]:
arr[arr>2]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Arthmetic

In [140]:
arr2=np.arange(0,30)

In [141]:
arr2 * arr2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [142]:
arr2 + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [143]:
# warning divise by zero 
arr2 / arr2

C:\Users\smart\AppData\Local\Temp\ipykernel_8568\3053098687.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr2 / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [144]:
arr2 - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [147]:
#power 

arr2 ** 3 

array([    0,     1,     8,    27,    64,   125,   216,   343,   512,
         729,  1000,  1331,  1728,  2197,  2744,  3375,  4096,  4913,
        5832,  6859,  8000,  9261, 10648, 12167, 13824, 15625, 17576,
       19683, 21952, 24389], dtype=int32)

In [146]:
np.sqrt(arr2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [149]:
np.exp(arr2)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12])

In [150]:
np.max(arr) # same as arr.max()

99

In [151]:
np.sin(arr)

array([-0.99920683, -0.99920683, -0.99920683, -0.99920683, -0.99920683,
       -0.99920683, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [152]:
np.log(arr)

array([4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985,
       4.59511985, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [153]:
np.cos(arr)

array([ 0.03982088,  0.03982088,  0.03982088,  0.03982088,  0.03982088,
        0.03982088,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901])